import {StyleSheet} from 'react-native';
import {Colors} from '../../constants';
import {
  responsiveFontSize,
  responsiveHeight,
  responsiveWidth,
} from 'react-native-responsive-dimensions';

export default StyleSheet.create({
  container: {padding: 10},
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  header: {fontSize: 20, fontWeight: '700', color: '#333333'},
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    // marginBottom: 12,
    justifyContent: 'space-between',
    width: '100%', // Fixed width for each item
    // paddingVerticalVertical: 10,
    // paddingHorizontal: 8,
    backgroundColor: Colors.transparent,
    // overflow: 'hidden',
    marginVertical: 10,
  },
  picker: {
    flex: 1,
    height: 50,
    borderColor: '#dcdcdc',
    borderWidth: 1,
    paddingHorizontal: 12,
    borderRadius: 10,
    fontSize: 16,
  },
  input: {
    // flex: 1,
    height: 50,
    borderColor: Colors.primary,
    borderWidth: 1,
    paddingHorizontal: 12,
    borderRadius: 10,
    fontSize: 16,
    width: '25%',
    // fontFamily: 'Roboto-Regular',
    // fontSize: 16,
    // height: 40,
    // opacity: 1,
    // borderBottomColor: Colors.primary,
    // borderBottomWidth: 1,
  },
  nameInput: {
    fontFamily: 'Roboto-Regular',
    height: 50,
    borderColor: Colors.primary,
    borderWidth: 1,
    paddingHorizontal: 12,
    marginBottom: 20,
    borderRadius: 10,
    fontSize: 18,
  },
  labelStyle: {
    color: Colors.white,
    fontSize: responsiveFontSize(2.3),
    fontFamily: 'Roboto-Medium',
  },
  buttonContainerStyle: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: Colors.primary,
    borderRadius: responsiveWidth(2),
    elevation: 5,
    justifyContent: 'center',
    // marginTop: responsiveHeight(3),
    // padding: responsiveWidth(2),
    // paddingHorizontal: responsiveWidth(3),
    width: responsiveWidth(40),
    height: responsiveHeight(5.5),
  },
  configContainer: {
    marginBottom: 10,
    padding: 12,
    backgroundColor: '#f9f9f9',
    borderRadius: 10,
    shadowColor: '#000000',
    shadowOpacity: 0.1,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 4,
    elevation: 2,
  },
  configRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  configName: {
    color: Colors.textColor,
    fontFamily: 'Roboto-Regular',
    fontSize: 18,
  },
  saveButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: 12,
    borderRadius: 10,
    marginBottom: 20,
    alignItems: 'center',
  },
  saveButtonText: {color: '#ffffff', fontSize: 16, fontWeight: '500'},
  applyButton: {
    backgroundColor: '#007BFF',
    paddingVertical: 10,
    borderRadius: 8,
    marginTop: 10,
    alignItems: 'center',
  },
  applyButtonText: {color: '#ffffff', fontSize: 14, fontWeight: '500'},
  message: {
    fontFamily: 'Roboto-Medium',
    fontSize: 16,
    color: Colors.primary,
    textAlign: 'center',
    marginVertical: 5,
  },
  modalContainer: {
    flex: 1,
    // justifyContent: 'center',
    // alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: '100%',
    height: '80%',
    borderRadius: 10,
    padding: 20,
    elevation: 5,
  },
  scrollViewContent: {
    paddingBottom: 20, // Add extra padding at the bottom for scrolling
  },
  modalHeader: {
    color: Colors.primary,
    fontFamily: 'Roboto-Medium',
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 15,
    textAlign: 'center',
  },
  modalRow: {
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: Colors.primary,
  },
  modalTitle: {
    fontFamily: 'Roboto-Medium',
    color: Colors.black,
    fontSize: 18,
  },
  modalText: {
    fontFamily: 'Roboto-Regular',
    color: Colors.textColor,
    fontSize: 18,
    marginLeft: 10,
  },
  closeButton: {
    marginTop: 20,
    backgroundColor: '#007BFF',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center',
  },
  closeButtonText: {
    color: '#ffffff',
    fontSize: 16,
  },
  titleStyle: {
    fontSize: responsiveFontSize(2.5),
    fontFamily: 'Roboto-Medium',
  },
  containerStyle: {
    alignItems: 'center',
    // alignSelf: 'center',
  },
});
