import {StyleSheet} from 'react-native';
import {Colors} from '../../constants';
import {
  responsiveFontSize,
  responsiveHeight,
  responsiveWidth,
} from 'react-native-responsive-dimensions';

export default StyleSheet.create({
  contentContainerStyle: {paddingHorizontal: responsiveWidth(4)},
  container: {
    alignItems: 'center',
    paddingVertical: responsiveWidth(1),
    paddingTop: 10,
  },
  pickerContainer: {
    alignItems: 'center',
    backgroundColor: Colors.primary,
    borderRadius: responsiveWidth(2),
    flexDirection: 'row',
    overflow: 'hidden',
    alignSelf: 'center',
    justifyContent: 'center',
    height: responsiveHeight(5.5),
    width: responsiveWidth(40),
  },
  pickerText: {
    color: Colors.white,
    fontSize: responsiveFontSize(2),
  },
  input: {
    fontFamily: 'Roboto-Medium',
    fontSize: responsiveFontSize(2),
    margin: 0,
    padding: 0,
    flex: 1,
  },
  entry: {
    alignItems: 'center',
    alignSelf: 'center',
    borderColor: Colors.primary,
    borderRadius: responsiveWidth(2),
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: responsiveHeight(2.5),
    padding: responsiveWidth(3.5),
    width: responsiveWidth(90),
  },
  semesterContainer: {flex: 1},
  semesterText: {
    color: Colors.white,
    fontFamily: 'Roboto-Medium',
    fontSize: responsiveFontSize(2),
  },
  modalContent: {
    borderColor: Colors.primary,
    borderTopLeftRadius: responsiveWidth(5),
    borderTopRightRadius: responsiveWidth(5),
    borderWidth: 1,
    borderBottomWidth: 0,
    padding: 0,
    marginHorizontal: responsiveWidth(-5.5),
    paddingVertical: responsiveWidth(5),
  },
  modalItem: {
    fontFamily: 'Roboto-Regular',
    fontSize: responsiveFontSize(2.1),
    textAlign: 'justify',
  },
  modalTitle: {
    alignItems: 'center',
    alignSelf: 'center',
    color: Colors.primary,
    fontFamily: 'Roboto-Medium',
    fontSize: responsiveFontSize(2.6),
    marginBottom: responsiveHeight(2),
  },
  modalButton: {
    alignItems: 'center',
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: responsiveWidth(2.5),
    width: responsiveWidth(75),
  },
  text1Style: {
    fontFamily: 'Roboto-Light',
    fontSize: responsiveFontSize(1.8),
  },
  mainView: {
    flex: 1,
    padding: responsiveWidth(5),
  },
  headerView: {
    alignItems: 'center',
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: responsiveHeight(2),
    width: responsiveWidth(90),
  },
  switchViewStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: responsiveWidth(2),
    borderColor: Colors.primary,
    padding: responsiveWidth(2.5),
  },
  switchText: {fontSize: responsiveFontSize(2)},
  keyboardScrollViewStyle: {flexGrow: 0.6},
  textInputViewStyle: {flex: 0.5},
  crHrsViewStyle: {flex: 0.7, right: 5},
  labelStyle: {
    color: Colors.white,
    fontSize: responsiveFontSize(2.3),
    fontFamily: 'Roboto-Medium',
  },
  buttonContainerStyle: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: Colors.primary,
    borderRadius: responsiveWidth(2),
    elevation: 5,
    justifyContent: 'center',
    width: responsiveWidth(40),
    height: responsiveHeight(5.5),
  },
  modalView: {alignItems: 'center'},
  numbersViewStyle: {flex: 1, alignItems: 'flex-end'},
  viewStyle: {flex: 1},
});
