import {Dimensions, StyleSheet} from 'react-native';
import {Colors} from '../../constants';

const screenHeight = Dimensions.get('window').height;
const screenWidth = Dimensions.get('window').width;
export default StyleSheet.create({
  border: {
    borderColor: Colors.white,
    borderWidth: 0.5,
    flexDirection: 'row',
    marginTop: 10,
    width: screenWidth,
  },
  btnView: {
    alignItems: 'center',
    backgroundColor: Colors.secondary,
    flex: 1,
    justifyContent: 'center',
    marginTop: 8,
  },
  button: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: Colors.primary,
    borderRadius: 10,
    elevation: 5,
    height: 45,
    justifyContent: 'center',
    marginTop: 30,
    width: '40%',
  },
  buttonBlack: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: Colors.black,
    borderRadius: 10,
    elevation: 5,
    height: 45,
    justifyContent: 'center',
    marginTop: 30,
    width: '40%',
  },
  buttonText: {
    color: Colors.white,
    fontSize: 18,
    fontFamily: 'Roboto-Medium',
  },
  buttonTextWhite: {
    color: Colors.white,
    fontSize: 18,
    fontFamily: 'Roboto-Medium',
  },
  buttonView: {
    alignItems: 'center',
    flex: 0.5,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: '100%',
  },
  configText: {
    fontFamily: 'Roboto-Light',
    fontSize: 16,
    color: Colors.white,
  },
  container: {
    alignItems: 'center',
    flex: 1,
    marginTop: 20,
    // padding: 10,
    // width: '90%',
  },
  contentStyle: {paddingHorizontal: 15},
  flexStyle: {flex: 0.9},
  flexStyleView: {flex: 0.5},
  input: {
    alignSelf: 'flex-start',
    backgroundColor: 'transparent',
    borderBottomWidth: 1,
    borderRadius: 10,
    borderWidth: 0,
    fontFamily: 'Roboto-Regular',
    height: 40,
    padding: 5,
    width: '80%',
  },
  inputContainer: {
    alignItems: 'center',
    flex: 1,
  },
  keyboardViewStyle: {
    backgroundColor: Colors.secondaryLight, //#363c4c
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    marginBottom: -10,
  },
  mainContainer: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: Colors.secondary,
    flex: 1,
  },
  mainView: {backgroundColor: Colors.secondary, flex: 1, paddingBottom: 80},
  primaryButton: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: Colors.primary,
    borderRadius: 10,
    bottom: 10,
    elevation: 5,
    height: 45,
    justifyContent: 'center',
    marginTop: 30,
    width: screenWidth / 2,
  },
  result: {
    color: Colors.white,
    fontWeight: 'Roboto-Medium',
    // width: '100%',
  },
  resultContainer: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    // justifyContent: 'space-evenly',
    // width: '100%',
  },
  resultTextView: {alignItems: 'center', flex: 1, left: 10},
  resultView: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  scrollView: {
    height: screenHeight / 1.6,
  },
  row: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    // marginHorizontal: 10,
    marginLeft: 20,
    paddingVertical: 5,
    width: '100%',
  },
  tag: {
    color: Colors.white,
    flex: 1,
    fontFamily: 'Roboto-Medium',
    fontSize: 18,
    textAlign: 'center',
  },
});
