import {
  ANDROID_PACKAGE_NAME,
  GRADIFY_APP_LINK,
  WEBSITE_URL,
  INSTAGRAM_URL,
  CONTACT_US_URL,
} from './Utilities';

export {
  ANDROID_PACKAGE_NAME,
  GRADIFY_APP_LINK,
  WEBSITE_URL,
  INSTAGRAM_URL,
  CONTACT_US_URL,
};
